// -----------------------------------------------------------------------
// <copyright file="AgentSkillStoreJsonContext.cs" company="Petabridge, LLC">
//      Copyright (C) 2026 - 2026 Petabridge, LLC <https://petabridge.com>
// </copyright>
// -----------------------------------------------------------------------
using System.Text.Json.Serialization;

namespace AgentSkillStore.Server.Models;

/// <summary>
/// JSON serialization context for AOT compilation support.
/// </summary>
[JsonSerializable(typeof(RfcSkillIndex))]
[JsonSerializable(typeof(RfcSkillEntry))]
[JsonSerializable(typeof(RfcResourceEntry))]
[JsonSerializable(typeof(SkillUploadRequest))]
[JsonSerializable(typeof(SkillUploadResponse))]
[JsonSerializable(typeof(IReadOnlyList<SkillResourceUploadMetadata>))]
[JsonSerializable(typeof(SubAgentUploadResponse))]
[JsonSerializable(typeof(SkillSummary))]
[JsonSerializable(typeof(SkillVersionSummary))]
[JsonSerializable(typeof(SkillResourceSummary))]
[JsonSerializable(typeof(SubAgentSummary))]
[JsonSerializable(typeof(SubAgentVersionSummary))]
[JsonSerializable(typeof(IReadOnlyList<SkillSummary>))]
[JsonSerializable(typeof(IReadOnlyList<SkillVersionSummary>))]
[JsonSerializable(typeof(IReadOnlyList<SkillResourceSummary>))]
[JsonSerializable(typeof(IReadOnlyList<SubAgentSummary>))]
[JsonSerializable(typeof(IReadOnlyList<SubAgentVersionSummary>))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(CreateApiKeyRequest))]
[JsonSerializable(typeof(CreateApiKeyResponse))]
[JsonSerializable(typeof(ApiKeySummary))]
[JsonSerializable(typeof(IReadOnlyList<ApiKeySummary>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(AppInfoResponse))]
[JsonSerializable(typeof(IReadOnlyList<CheckUpdateRequestItem>))]
[JsonSerializable(typeof(IReadOnlyList<CheckUpdateResponseItem>))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(EnterpriseSessionUser))]
[JsonSerializable(typeof(LocalLoginRequest))]
[JsonSerializable(typeof(EnterpriseOwner))]
[JsonSerializable(typeof(EnterpriseCategory))]
[JsonSerializable(typeof(EnterpriseFilesystemPermissions))]
[JsonSerializable(typeof(EnterpriseNetworkPermissions))]
[JsonSerializable(typeof(EnterprisePermissions))]
[JsonSerializable(typeof(EnterpriseSkillVersionSummary))]
[JsonSerializable(typeof(EnterpriseSkillFileSummary))]
[JsonSerializable(typeof(EnterpriseReviewHistory))]
[JsonSerializable(typeof(IReadOnlyList<EnterpriseReviewHistory>))]
[JsonSerializable(typeof(EnterpriseSkillSummary))]
[JsonSerializable(typeof(IReadOnlyList<EnterpriseSkillSummary>))]
[JsonSerializable(typeof(CreatePublicationRequest))]
[JsonSerializable(typeof(PublicationResponse))]
[JsonSerializable(typeof(EnterprisePublicationSummary))]
[JsonSerializable(typeof(IReadOnlyList<EnterprisePublicationSummary>))]
[JsonSerializable(typeof(EnterpriseReviewSummary))]
[JsonSerializable(typeof(IReadOnlyList<EnterpriseReviewSummary>))]
[JsonSerializable(typeof(ReviewDecisionRequest))]
[JsonSerializable(typeof(EnterpriseAuditEvent))]
[JsonSerializable(typeof(IReadOnlyList<EnterpriseAuditEvent>))]
[JsonSerializable(typeof(InstallReference))]
[JsonSerializable(typeof(EnterpriseError))]
[JsonSerializable(typeof(EnterpriseSystemStatus))]
[JsonSerializable(typeof(EnterpriseCliStatus))]
[JsonSerializable(typeof(List<ApiKeySummary>))]
[JsonSerializable(typeof(GovernanceTeam))]
[JsonSerializable(typeof(IReadOnlyList<GovernanceTeam>))]
[JsonSerializable(typeof(GovernanceCategory))]
[JsonSerializable(typeof(IReadOnlyList<GovernanceCategory>))]
[JsonSerializable(typeof(NativeRootManifest))]
[JsonSerializable(typeof(NativeVersionLinks))]
[JsonSerializable(typeof(NativeSkillCollectionIndex))]
[JsonSerializable(typeof(NativeSkillCollectionPage))]
[JsonSerializable(typeof(NativeSkillIdentityIndex))]
[JsonSerializable(typeof(NativeSkillVersionDetail))]
[JsonSerializable(typeof(NativeSubAgentCollectionIndex))]
[JsonSerializable(typeof(NativeSubAgentCollectionPage))]
[JsonSerializable(typeof(NativeSubAgentIdentityIndex))]
[JsonSerializable(typeof(NativeSubAgentVersionDetail))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
public partial class AgentSkillStoreJsonContext : JsonSerializerContext;
